In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Crop_recommendation.csv')

In [3]:
df

        Id    N   P   K  temperature   humidity        ph    rainfall   label
0        1   90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1        2   85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2        3   60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3        4   74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4        5   78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...    ...  ...  ..  ..          ...        ...       ...         ...     ...
2195  2196  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196  2197   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  2198  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  2199  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  2200  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 9 columns]

In [ ]:
Q1 = df['N'].quantile(0.25)
Q3 = df['N'].quantile(0.75)

In [ ]:
print("75th quartile: ",Q3)
print("25th quartile: ",Q1)

75th quartile:  84.25
25th quartile:  21.0

In [ ]:
IQR = Q3 - Q1
print ("IQR: ",IQR)

IQR:  63.25

In [ ]:
upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

In [ ]:
df[df['N'] > upper_limit].count()

Id             0
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
Q1 = df['P'].quantile(0.25)
Q3 = df['P'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

df[df['P'] > upper_limit].count()
df[df['P'] < lower_limit].count()

Id             0
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
Q1 = df['K'].quantile(0.25)
Q3 = df['K'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

df[df['K'] > upper_limit].count()
df[df['K'] < lower_limit].count()

Id             0
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
Q1 = df['temperature'].quantile(0.25)
Q3 = df['temperature'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

df[df['temperature'] > upper_limit].count()
df[df['temperature'] < lower_limit].count()

Id             38
N              38
P              38
K              38
temperature    38
humidity       38
ph             38
rainfall       38
label          38
dtype: int64

In [ ]:
Q1 = df['humidity'].quantile(0.25)
Q3 = df['humidity'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

df[df['humidity'] > upper_limit].count()
df[df['humidity'] < lower_limit].count()

Id             30
N              30
P              30
K              30
temperature    30
humidity       30
ph             30
rainfall       30
label          30
dtype: int64

In [ ]:
Q1 = df['ph'].quantile(0.25)
Q3 = df['ph'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

df[df['ph'] > upper_limit].count()
df[df['ph'] < lower_limit].count()

Id             18
N              18
P              18
K              18
temperature    18
humidity       18
ph             18
rainfall       18
label          18
dtype: int64

In [ ]:
Q1 = df['rainfall'].quantile(0.25)
Q3 = df['rainfall'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

df[df['rainfall'] > upper_limit].count()
df[df['rainfall'] < lower_limit].count()

Id             0
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
Q1 = df['temperature'].quantile(0.25)
Q3 = df['temperature'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

new_df1 = df[(df['temperature'] < upper_limit) & (df['temperature']>lower_limit)]
new_df1.shape

(2114, 9)

In [ ]:
Q1 = df['humidity'].quantile(0.25)
Q3 = df['humidity'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

new_df2 = df[(df['humidity'] < upper_limit) & (df['humidity']>lower_limit)]
new_df2.shape

(2170, 9)

In [ ]:
Q1 = df['ph'].quantile(0.25)
Q3 = df['ph'].quantile(0.75)

IQR = Q3 - Q1

upper_limit=Q3 + 1.5*IQR
lower_limit=Q1 - 1.5*IQR

new_df3 = df[(df['ph'] < upper_limit) & (df['ph']>lower_limit)]
new_df3.shape

(2143, 9)

In [ ]:
print(new_df1)

        Id    N   P   K  temperature   humidity        ph    rainfall   label
0        1   90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1        2   85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2        3   60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3        4   74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4        5   78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...    ...  ...  ..  ..          ...        ...       ...         ...     ...
2195  2196  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196  2197   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  2198  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  2199  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  2200  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2114 rows x 9 columns]

In [ ]:
dfx=pd.merge(new_df1,new_df2,on='Id')

In [ ]:
df_upd=pd.merge(dfx,new_df3,on='Id')

In [ ]:
print(df_upd)

        Id  N_x  P_x  K_x  temperature_x  humidity_x      ph_x  rainfall_x  \
0        1   90   42   43      20.879744   82.002744  6.502985  202.935536
1        2   85   58   41      21.770462   80.319644  7.038096  226.655537
2        3   60   55   44      23.004459   82.320763  7.840207  263.964248
3        4   74   35   40      26.491096   80.158363  6.980401  242.864034
4        5   78   42   42      20.130175   81.604873  7.628473  262.717340
...    ...  ...  ...  ...            ...         ...       ...         ...
2023  2196  107   34   32      26.774637   66.413269  6.780064  177.774507
2024  2197   99   15   27      27.417112   56.636362  6.086922  127.924610
2025  2198  118   33   30      24.131797   67.225123  6.362608  173.322839
2026  2199  117   32   34      26.272418   52.127394  6.758793  127.175293
2027  2200  104   18   30      23.603016   60.396475  6.779833  140.937041

     label_x  N_y  ...  rainfall_y  label_y    N   P   K  temperature  \
0       rice   90  ...  202.935536     rice   90  42  43    20.879744
1       rice   85  ...  226.655537     rice   85  58  41    21.770462
2       rice   60  ...  263.964248     rice   60  55  44    23.004459
3       rice   74  ...  242.864034     rice   74  35  40    26.491096
4       rice   78  ...  262.717340     rice   78  42  42    20.130175
...      ...  ...  ...         ...      ...  ...  ..  ..          ...
2023  coffee  107  ...  177.774507   coffee  107  34  32    26.774637
2024  coffee   99  ...  127.924610   coffee   99  15  27    27.417112
2025  coffee  118  ...  173.322839   coffee  118  33  30    24.131797
2026  coffee  117  ...  127.175293   coffee  117  32  34    26.272418
2027  coffee  104  ...  140.937041   coffee  104  18  30    23.603016

       humidity        ph    rainfall   label
0     82.002744  6.502985  202.935536    rice
1     80.319644  7.038096  226.655537    rice
2     82.320763  7.840207  263.964248    rice
3     80.158363  6.980401  242.864034    rice
4     81.604873  7.628473  262.717340    rice
...         ...       ...         ...     ...
2023  66.413269  6.780064  177.774507  coffee
2024  56.636362  6.086922  127.924610  coffee
2025  67.225123  6.362608  173.322839  coffee
2026  52.127394  6.758793  127.175293  coffee
2027  60.396475  6.779833  140.937041  coffee

[2028 rows x 25 columns]

In [ ]:
df_upd= df_upd[df_upd.columns[1:9]]

In [ ]:
df_upd.columns=['N','P','K','temperature','humidity','ph','rainfall','label']

In [ ]:
print(df_upd)

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2023  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2024   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2025  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2026  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2027  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2028 rows x 8 columns]

In [ ]:
df_upd.to_csv('CropRecommenderUpdated.csv')